#!/usr/bin/env python3
"""Schema contract for context packets generated by the task router."""

from __future__ import annotations

import re
from pathlib import Path, PurePosixPath
from typing import Any

try:
    from scripts.common import sha256
except ModuleNotFoundError:  # Direct execution from scripts/
    from common import sha256


PACKET_SCHEMA_VERSION = 4
SUPPORTED_PACKET_SCHEMAS = {1, 2, 3, PACKET_SCHEMA_VERSION}
INTEGRITY_PACKET_SCHEMAS = {3, PACKET_SCHEMA_VERSION}
PACKET_COMPILER = "scripts/context_packet.py"
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")


def _is_relative_product_path(value: Any) -> bool:
    if not isinstance(value, str) or not value:
        return False
    path = PurePosixPath(value)
    return not path.is_absolute() and ".." not in path.parts


def _validate_path_list(packet: dict[str, Any], field: str, errors: list[str]) -> None:
    value = packet.get(field)
    if not isinstance(value, list):
        errors.append(f"packet.{field} must be a list")
        return
    for index, item in enumerate(value):
        if not _is_relative_product_path(item):
            errors.append(f"packet.{field}[{index}] must be a product-relative path")


def validate_packet_contract(packet: dict[str, Any], context_path: Path | None = None) -> list[str]:
    """Return stable, user-readable errors instead of trusting packet JSON shape."""

    errors: list[str] = []
    schema_version = packet.get("schema_version")
    if schema_version not in SUPPORTED_PACKET_SCHEMAS:
        errors.append(f"unsupported packet.schema_version: {schema_version!r}")

    for field in ["authority", "task_id", "product", "operation", "report_path", "operator_brief_path"]:
        if not isinstance(packet.get(field), str) or not packet[field]:
            errors.append(f"packet.{field} must be a non-empty string")

    if not isinstance(packet.get("target"), dict):
        errors.append("packet.target must be an object")

    for field in ["instruction_files", "operation_outputs", "allowed_write_paths"]:
        _validate_path_list(packet, field, errors)
    for field in ["report_path", "operator_brief_path"]:
        if field in packet and not _is_relative_product_path(packet[field]):
            errors.append(f"packet.{field} must be a product-relative path")

    for field in ["validation"]:
        value = packet.get(field)
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            errors.append(f"packet.{field} must be a list of strings")

    if schema_version in {1, 2, 3}:
        value = packet.get("acceptance_criteria")
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            errors.append("legacy packet.acceptance_criteria must be a list of strings")

    for field in ["estimated_context_tokens", "max_context_tokens"]:
        value = packet.get(field)
        if not isinstance(value, int) or isinstance(value, bool) or value < 0:
            errors.append(f"packet.{field} must be a non-negative integer")

    if schema_version in INTEGRITY_PACKET_SCHEMAS:
        for field in ["prompt_instruction_tokens", "input_tokens"]:
            value = packet.get(field)
            if not isinstance(value, int) or isinstance(value, bool) or value < 0:
                errors.append(f"packet.{field} must be a non-negative integer")
        if not isinstance(packet.get("context_profile"), str) or not packet["context_profile"]:
            errors.append("packet.context_profile must be a non-empty string")
        boundaries = packet.get("boundary_enforcement")
        if not isinstance(boundaries, list) or not boundaries or not all(isinstance(item, str) and item for item in boundaries):
            errors.append("packet.boundary_enforcement must be a non-empty list of strings")
        gate = packet.get("evaluation_gate")
        if gate is not None and (not isinstance(gate, str) or not gate):
            errors.append("packet.evaluation_gate must be null or a non-empty string")

    runtime = packet.get("execution_runtime")
    if runtime is not None:
        if not isinstance(runtime, dict):
            errors.append("packet.execution_runtime must be an object")
        else:
            if runtime.get("kind") != "dsh":
                errors.append("packet.execution_runtime.kind must be 'dsh'")
            if runtime.get("adapter") != "scripts/outline_runtime.py":
                errors.append("packet.execution_runtime.adapter must be 'scripts/outline_runtime.py'")
            if runtime.get("interface_version") != 1:
                errors.append("packet.execution_runtime.interface_version must be 1")
            capabilities = runtime.get("capabilities")
            if not isinstance(capabilities, list) or not capabilities or not all(
                isinstance(item, str) and item for item in capabilities
            ):
                errors.append("packet.execution_runtime.capabilities must be a non-empty list of strings")
        if packet.get("operation") != "outline":
            errors.append("DeepSeek Harness runtime is allowed only for outline")

        runtime_owned = packet.get("runtime_owned_paths")
        if not isinstance(runtime_owned, list):
            errors.append("packet.runtime_owned_paths must be a list")
        else:
            for index, item in enumerate(runtime_owned):
                if not _is_relative_product_path(item):
                    errors.append(f"packet.runtime_owned_paths[{index}] must be a product-relative path")
            task_id = packet.get("task_id")
            expected_runtime_owned = {
                f"tasks/{task_id}/runtime-trace.jsonl",
                f"tasks/{task_id}/runtime-run.json",
            }
            if set(runtime_owned) != expected_runtime_owned:
                errors.append("packet.runtime_owned_paths must contain only the task trace and run record")
    elif "runtime_owned_paths" in packet:
        errors.append("packet.runtime_owned_paths requires packet.execution_runtime")

    inputs = packet.get("inputs")
    if not isinstance(inputs, list):
        errors.append("packet.inputs must be a list of compiled input records")
    else:
        for index, record in enumerate(inputs):
            if not isinstance(record, dict):
                errors.append(
                    f"packet.inputs[{index}] must be a compiled record with path, sha256 and bytes; "
                    "create tasks with scripts/task.py create"
                )
                continue
            path = record.get("path")
            digest = record.get("sha256")
            size = record.get("bytes")
            if not _is_relative_product_path(path):
                errors.append(f"packet.inputs[{index}].path must be a product-relative path")
            if not isinstance(digest, str) or not SHA256_PATTERN.fullmatch(digest):
                errors.append(f"packet.inputs[{index}].sha256 must be a SHA-256 digest")
            if not isinstance(size, int) or isinstance(size, bool) or size < 0:
                errors.append(f"packet.inputs[{index}].bytes must be a non-negative integer")

    baselines = packet.get("output_baselines")
    if not isinstance(baselines, list):
        errors.append("packet.output_baselines must be a list of compiled output records")
    else:
        for index, record in enumerate(baselines):
            if not isinstance(record, dict):
                errors.append(f"packet.output_baselines[{index}] must be an object with path and sha256")
                continue
            if not _is_relative_product_path(record.get("path")):
                errors.append(f"packet.output_baselines[{index}].path must be a product-relative path")
            digest = record.get("sha256")
            if digest is not None and (not isinstance(digest, str) or not SHA256_PATTERN.fullmatch(digest)):
                errors.append(f"packet.output_baselines[{index}].sha256 must be null or a SHA-256 digest")

    outputs = packet.get("operation_outputs")
    allowed = packet.get("allowed_write_paths")
    if isinstance(outputs, list) and isinstance(allowed, list):
        for path in outputs:
            if path not in allowed:
                errors.append(f"operation output is outside packet write scope: {path}")
    for field in ["report_path", "operator_brief_path"]:
        path = packet.get(field)
        if isinstance(path, str) and isinstance(allowed, list) and path not in allowed:
            errors.append(f"packet.{field} is outside packet write scope")
    runtime_owned = packet.get("runtime_owned_paths", [])
    if isinstance(runtime_owned, list) and isinstance(allowed, list):
        for path in runtime_owned:
            if path in allowed:
                errors.append(f"runtime-owned path must stay outside model write scope: {path}")

    if schema_version in INTEGRITY_PACKET_SCHEMAS:
        if packet.get("compiler") != PACKET_COMPILER:
            errors.append(f"packet.compiler must be {PACKET_COMPILER!r}")
        context_digest = packet.get("context_sha256")
        if not isinstance(context_digest, str) or not SHA256_PATTERN.fullmatch(context_digest):
            errors.append("packet.context_sha256 must be a SHA-256 digest")
        elif context_path is not None:
            if not context_path.is_file():
                errors.append("missing compiled context packet")
            elif sha256(context_path) != context_digest:
                errors.append("compiled context packet is stale or was edited manually")

    return errors
